In [20]:
import pandas as pd

In [21]:
amherst=pd.read_csv('../../amherstPRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','amherst','flag']).drop(['row','flag'],axis=1)
amherst.head()

                amherst
year month day
1893 1     2      215.0
           3        0.0
           4        0.0
           5        0.0
           6        4.0

In [22]:
bedford=pd.read_csv('../../bedfordPRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','bedford','flag']).drop(['row','flag'],axis=1)

bedford.head()

                bedford
year month day
1957 5     2        NaN
           3        NaN
           4        NaN
           5        NaN
           6        0.0

In [23]:
bluehill=pd.read_csv('../../bluehillPRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','bluehill','flag']).drop(['row','flag'],axis=1)

In [24]:
gb=pd.read_csv('../../gbPRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','gb','flag']).drop(['row','flag'],axis=1)

In [25]:
lawrence=pd.read_csv('../../lawrencePRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','lawrence','flag']).drop(['row','flag'],axis=1)

In [26]:
nb=pd.read_csv('../../nbPRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','nb','flag']).drop(['row','flag'],axis=1)

In [27]:
pk=pd.read_csv('../../pkPRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','pk','flag']).drop(['row','flag'],axis=1)

In [28]:
ptown=pd.read_csv('../../ptownPRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','ptown','flag']).drop(['row','flag'],axis=1)

In [29]:
reading=pd.read_csv('../../readingPRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','reading','flag']).drop(['row','flag'],axis=1)

In [30]:
taunton=pd.read_csv('../../tauntonPRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','taunton','flag']).drop(['row','flag'],axis=1)

In [31]:
walpole=pd.read_csv('../../walpolePRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','walpole','flag']).drop(['row','flag'],axis=1)

In [32]:
wm=pd.read_csv('../../wmPRECIP.csv', header=0,
        index_col=['year','month','day'],names=['row','year','month','day','wm','flag']).drop(['row','flag'],axis=1)

In [33]:
rain = amherst.join([bedford,bluehill,gb,lawrence,nb,pk,ptown,reading,taunton,walpole,wm],how='outer')
rain

                amherst  bedford  bluehill  gb  lawrence    nb     pk  ptown  \
year month day
0    0     0        0.0      NaN       NaN NaN       NaN   NaN    NaN    NaN
1893 1     2      215.0      NaN      22.0 NaN      76.0   NaN  117.0    NaN
           3        0.0      NaN      73.0 NaN       0.0  40.0    0.0    NaN
           4        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           5        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           6        4.0      NaN       0.0 NaN      31.0   NaN   45.0    NaN
           7        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           8        0.0      NaN       0.0 NaN       0.0   6.0    0.0    NaN
           9        NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           10       6.0      NaN       0.0 NaN      42.0   NaN   38.0    NaN
           11       NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           12       0.0      NaN       0.0 NaN       0.0   5.0    0.0    NaN
           13       NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           14       6.0      NaN       0.0 NaN       5.0   NaN    0.0    NaN
           15       6.0      NaN       0.0 NaN       0.0  65.0   18.0    NaN
           16       6.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           17       NaN      NaN       0.0 NaN       0.0   NaN    4.0    NaN
           18       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           19       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           20       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           21       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           22       0.0      NaN       0.0 NaN       3.0   NaN    0.0    NaN
           23       NaN      NaN       0.0 NaN       0.0   NaN    8.0    NaN
           24       6.0      NaN       0.0 NaN      10.0   NaN    0.0    NaN
           25       6.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           26       6.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           27       NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           28       0.0      NaN       0.0 NaN      28.0   NaN   58.0    NaN
           29       NaN      NaN      36.0 NaN       0.0   NaN    0.0    NaN
           30       NaN      NaN       0.0 NaN       6.0   NaN    0.0    NaN
...                 ...      ...       ...  ..       ...   ...    ...    ...
2014 12    2        0.0      NaN       1.0 NaN       0.0   NaN    0.0    NaN
           3       47.0      NaN      33.0 NaN      55.0   NaN   24.0    NaN
           4        0.0      NaN       8.0 NaN       2.0   NaN    0.0    NaN
           5        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           6       43.0      NaN      37.0 NaN      60.0   NaN   41.0    NaN
           7       53.0      NaN      89.0 NaN      66.0   NaN   96.0    NaN
           8        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           9        1.0      NaN      16.0 NaN       0.0   NaN  215.0    NaN
           10     158.0      NaN     315.0 NaN     210.0   NaN   20.0    NaN
           11      29.0      NaN      37.0 NaN      26.0   NaN   28.0    NaN
           12       5.0      NaN       4.0 NaN       3.0   NaN    0.0    NaN
           13       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           14       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           15       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           16       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           17      25.0      NaN      42.0 NaN      39.0   NaN   55.0    NaN
           18       0.0      NaN       2.0 NaN      10.0   NaN    3.0    NaN
           19       0.0      NaN       1.0 NaN       0.0   NaN    0.0    NaN
           20       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           21       2.0      NaN      19.0 NaN       0.0   NaN   30.0    NaN
           22       0.0      NaN       0.0 NaN       0.0   NaN    6.0    NaN
           23       8.0      NaN       8.0 NaN      15.0   NaN   15.0    NaN
           24      20.0      NaN      31.0 NaN      35.0   NaN   21.0    NaN
           25      42.0      NaN      62.0 NaN      52.0   NaN    0.0    NaN
           26       0.0      NaN      14.0 NaN       6.0   NaN    0.0    NaN
           27       0.0      NaN       0.0 NaN       0.0   NaN    8.0    NaN
           28       0.0      NaN       0.0 NaN       4.0   NaN    0.0    NaN
           29       1.0      NaN       2.0 NaN       0.0   NaN    0.0    NaN
           30       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           31       0.0      NaN       0.0 NaN       0.0   NaN    NaN    NaN

                reading  taunton  walpole  wm
year month day
0    0     0        NaN      NaN      NaN NaN
1893 1     2        NaN    123.0      NaN NaN
           3        NaN      0.0      NaN NaN
           4        NaN      0.0      NaN NaN
           5        NaN      0.0      NaN NaN
           6        NaN    143.0      NaN NaN
           7        NaN      0.0      NaN NaN
           8        NaN      0.0      NaN NaN
           9        NaN      0.0      NaN NaN
           10       NaN     24.0      NaN NaN
           11       NaN      0.0      NaN NaN
           12       NaN      0.0      NaN NaN
           13       NaN      5.0      NaN NaN
           14       NaN      0.0      NaN NaN
           15       NaN     50.0      NaN NaN
           16       NaN      0.0      NaN NaN
           17       NaN      0.0      NaN NaN
           18       NaN     10.0      NaN NaN
           19       NaN      0.0      NaN NaN
           20       NaN      0.0      NaN NaN
           21       NaN      0.0      NaN NaN
           22       NaN      0.0      NaN NaN
           23       NaN      5.0      NaN NaN
           24       NaN      0.0      NaN NaN
           25       NaN      0.0      NaN NaN
           26       NaN      0.0      NaN NaN
           27       NaN      0.0      NaN NaN
           28       NaN      0.0      NaN NaN
           29       NaN     50.0      NaN NaN
           30       NaN      0.0      NaN NaN
...                 ...      ...      ...  ..
2014 12    2        6.0      NaN      0.0 NaN
           3       58.0      NaN     33.0 NaN
           4        0.0      NaN      9.0 NaN
           5       13.0      NaN      0.0 NaN
           6      118.0      NaN     38.0 NaN
           7       13.0      NaN     87.0 NaN
           8        0.0      NaN      0.0 NaN
           9      363.0      NaN     10.0 NaN
           10      14.0      NaN    291.0 NaN
           11      18.0      NaN     14.0 NaN
           12       1.0      NaN      2.0 NaN
           13       0.0      NaN      0.0 NaN
           14       0.0      NaN      0.0 NaN
           15       0.0      NaN      0.0 NaN
           16       0.0      NaN      0.0 NaN
           17      35.0      NaN     39.0 NaN
           18       3.0      NaN      5.0 NaN
           19       0.0      NaN      1.0 NaN
           20       0.0      NaN      0.0 NaN
           21       0.0      NaN      2.0 NaN
           22       0.0      NaN      1.0 NaN
           23      19.0      NaN     11.0 NaN
           24      53.0      NaN     11.0 NaN
           25      15.0      NaN     50.0 NaN
           26       0.0      NaN     12.0 NaN
           27       0.0      NaN      0.0 NaN
           28       1.0      NaN      0.0 NaN
           29       0.0      NaN      5.0 NaN
           30       0.0      NaN      0.0 NaN
           31       0.0      NaN      0.0 NaN

[44530 rows x 12 columns]

Remove the one record for year, month, day = zero

In [34]:
rain.drop([0,0,0])

                amherst  bedford  bluehill  gb  lawrence    nb     pk  ptown  \
year month day
1893 1     2      215.0      NaN      22.0 NaN      76.0   NaN  117.0    NaN
           3        0.0      NaN      73.0 NaN       0.0  40.0    0.0    NaN
           4        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           5        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           6        4.0      NaN       0.0 NaN      31.0   NaN   45.0    NaN
           7        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           8        0.0      NaN       0.0 NaN       0.0   6.0    0.0    NaN
           9        NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           10       6.0      NaN       0.0 NaN      42.0   NaN   38.0    NaN
           11       NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           12       0.0      NaN       0.0 NaN       0.0   5.0    0.0    NaN
           13       NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           14       6.0      NaN       0.0 NaN       5.0   NaN    0.0    NaN
           15       6.0      NaN       0.0 NaN       0.0  65.0   18.0    NaN
           16       6.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           17       NaN      NaN       0.0 NaN       0.0   NaN    4.0    NaN
           18       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           19       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           20       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           21       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           22       0.0      NaN       0.0 NaN       3.0   NaN    0.0    NaN
           23       NaN      NaN       0.0 NaN       0.0   NaN    8.0    NaN
           24       6.0      NaN       0.0 NaN      10.0   NaN    0.0    NaN
           25       6.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           26       6.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           27       NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           28       0.0      NaN       0.0 NaN      28.0   NaN   58.0    NaN
           29       NaN      NaN      36.0 NaN       0.0   NaN    0.0    NaN
           30       NaN      NaN       0.0 NaN       6.0   NaN    0.0    NaN
           31       NaN      NaN       0.0 NaN       NaN   NaN    NaN    NaN
...                 ...      ...       ...  ..       ...   ...    ...    ...
2014 12    2        0.0      NaN       1.0 NaN       0.0   NaN    0.0    NaN
           3       47.0      NaN      33.0 NaN      55.0   NaN   24.0    NaN
           4        0.0      NaN       8.0 NaN       2.0   NaN    0.0    NaN
           5        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           6       43.0      NaN      37.0 NaN      60.0   NaN   41.0    NaN
           7       53.0      NaN      89.0 NaN      66.0   NaN   96.0    NaN
           8        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           9        1.0      NaN      16.0 NaN       0.0   NaN  215.0    NaN
           10     158.0      NaN     315.0 NaN     210.0   NaN   20.0    NaN
           11      29.0      NaN      37.0 NaN      26.0   NaN   28.0    NaN
           12       5.0      NaN       4.0 NaN       3.0   NaN    0.0    NaN
           13       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           14       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           15       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           16       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           17      25.0      NaN      42.0 NaN      39.0   NaN   55.0    NaN
           18       0.0      NaN       2.0 NaN      10.0   NaN    3.0    NaN
           19       0.0      NaN       1.0 NaN       0.0   NaN    0.0    NaN
           20       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           21       2.0      NaN      19.0 NaN       0.0   NaN   30.0    NaN
           22       0.0      NaN       0.0 NaN       0.0   NaN    6.0    NaN
           23       8.0      NaN       8.0 NaN      15.0   NaN   15.0    NaN
           24      20.0      NaN      31.0 NaN      35.0   NaN   21.0    NaN
           25      42.0      NaN      62.0 NaN      52.0   NaN    0.0    NaN
           26       0.0      NaN      14.0 NaN       6.0   NaN    0.0    NaN
           27       0.0      NaN       0.0 NaN       0.0   NaN    8.0    NaN
           28       0.0      NaN       0.0 NaN       4.0   NaN    0.0    NaN
           29       1.0      NaN       2.0 NaN       0.0   NaN    0.0    NaN
           30       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           31       0.0      NaN       0.0 NaN       0.0   NaN    NaN    NaN

                reading  taunton  walpole  wm
year month day
1893 1     2        NaN    123.0      NaN NaN
           3        NaN      0.0      NaN NaN
           4        NaN      0.0      NaN NaN
           5        NaN      0.0      NaN NaN
           6        NaN    143.0      NaN NaN
           7        NaN      0.0      NaN NaN
           8        NaN      0.0      NaN NaN
           9        NaN      0.0      NaN NaN
           10       NaN     24.0      NaN NaN
           11       NaN      0.0      NaN NaN
           12       NaN      0.0      NaN NaN
           13       NaN      5.0      NaN NaN
           14       NaN      0.0      NaN NaN
           15       NaN     50.0      NaN NaN
           16       NaN      0.0      NaN NaN
           17       NaN      0.0      NaN NaN
           18       NaN     10.0      NaN NaN
           19       NaN      0.0      NaN NaN
           20       NaN      0.0      NaN NaN
           21       NaN      0.0      NaN NaN
           22       NaN      0.0      NaN NaN
           23       NaN      5.0      NaN NaN
           24       NaN      0.0      NaN NaN
           25       NaN      0.0      NaN NaN
           26       NaN      0.0      NaN NaN
           27       NaN      0.0      NaN NaN
           28       NaN      0.0      NaN NaN
           29       NaN     50.0      NaN NaN
           30       NaN      0.0      NaN NaN
           31       NaN      0.0      NaN NaN
...                 ...      ...      ...  ..
2014 12    2        6.0      NaN      0.0 NaN
           3       58.0      NaN     33.0 NaN
           4        0.0      NaN      9.0 NaN
           5       13.0      NaN      0.0 NaN
           6      118.0      NaN     38.0 NaN
           7       13.0      NaN     87.0 NaN
           8        0.0      NaN      0.0 NaN
           9      363.0      NaN     10.0 NaN
           10      14.0      NaN    291.0 NaN
           11      18.0      NaN     14.0 NaN
           12       1.0      NaN      2.0 NaN
           13       0.0      NaN      0.0 NaN
           14       0.0      NaN      0.0 NaN
           15       0.0      NaN      0.0 NaN
           16       0.0      NaN      0.0 NaN
           17      35.0      NaN     39.0 NaN
           18       3.0      NaN      5.0 NaN
           19       0.0      NaN      1.0 NaN
           20       0.0      NaN      0.0 NaN
           21       0.0      NaN      2.0 NaN
           22       0.0      NaN      1.0 NaN
           23      19.0      NaN     11.0 NaN
           24      53.0      NaN     11.0 NaN
           25      15.0      NaN     50.0 NaN
           26       0.0      NaN     12.0 NaN
           27       0.0      NaN      0.0 NaN
           28       1.0      NaN      0.0 NaN
           29       0.0      NaN      5.0 NaN
           30       0.0      NaN      0.0 NaN
           31       0.0      NaN      0.0 NaN

[44529 rows x 12 columns]

In [35]:
rain.shape

(44530, 12)

In [36]:
rain.describe()

,amherst,bedford,bluehill,gb,lawrence,nb,pk,ptown,reading,taunton,walpole,wm
count,42804.000000,18839.000000,43998.000000,10904.000000,41848.000000,34297.000000,42817.000000,10462.000000,19920.000000,40182.000000,15334.000000,17420.000000
mean,11.777661,12.654175,13.338447,12.238903,10.875812,12.472053,13.047668,10.569107,13.316215,12.825195,13.126712,12.793685
std,31.666113,34.113732,35.815342,31.947438,32.808523,34.330250,36.848858,31.515477,36.189540,39.175181,35.671129,35.726312
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6.000000,6.000000,7.000000,7.000000,3.000000,6.000000,5.000000,2.000000,7.000000,4.000000,6.000000,4.000000
max,756.000000,783.000000,807.000000,583.000000,1020.000000,728.000000,820.000000,525.000000,767.000000,2565.000000,700.000000,639.000000

In [37]:
rain

                amherst  bedford  bluehill  gb  lawrence    nb     pk  ptown  \
year month day
0    0     0        0.0      NaN       NaN NaN       NaN   NaN    NaN    NaN
1893 1     2      215.0      NaN      22.0 NaN      76.0   NaN  117.0    NaN
           3        0.0      NaN      73.0 NaN       0.0  40.0    0.0    NaN
           4        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           5        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           6        4.0      NaN       0.0 NaN      31.0   NaN   45.0    NaN
           7        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           8        0.0      NaN       0.0 NaN       0.0   6.0    0.0    NaN
           9        NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           10       6.0      NaN       0.0 NaN      42.0   NaN   38.0    NaN
           11       NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           12       0.0      NaN       0.0 NaN       0.0   5.0    0.0    NaN
           13       NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           14       6.0      NaN       0.0 NaN       5.0   NaN    0.0    NaN
           15       6.0      NaN       0.0 NaN       0.0  65.0   18.0    NaN
           16       6.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           17       NaN      NaN       0.0 NaN       0.0   NaN    4.0    NaN
           18       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           19       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           20       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           21       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           22       0.0      NaN       0.0 NaN       3.0   NaN    0.0    NaN
           23       NaN      NaN       0.0 NaN       0.0   NaN    8.0    NaN
           24       6.0      NaN       0.0 NaN      10.0   NaN    0.0    NaN
           25       6.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           26       6.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           27       NaN      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           28       0.0      NaN       0.0 NaN      28.0   NaN   58.0    NaN
           29       NaN      NaN      36.0 NaN       0.0   NaN    0.0    NaN
           30       NaN      NaN       0.0 NaN       6.0   NaN    0.0    NaN
...                 ...      ...       ...  ..       ...   ...    ...    ...
2014 12    2        0.0      NaN       1.0 NaN       0.0   NaN    0.0    NaN
           3       47.0      NaN      33.0 NaN      55.0   NaN   24.0    NaN
           4        0.0      NaN       8.0 NaN       2.0   NaN    0.0    NaN
           5        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           6       43.0      NaN      37.0 NaN      60.0   NaN   41.0    NaN
           7       53.0      NaN      89.0 NaN      66.0   NaN   96.0    NaN
           8        0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           9        1.0      NaN      16.0 NaN       0.0   NaN  215.0    NaN
           10     158.0      NaN     315.0 NaN     210.0   NaN   20.0    NaN
           11      29.0      NaN      37.0 NaN      26.0   NaN   28.0    NaN
           12       5.0      NaN       4.0 NaN       3.0   NaN    0.0    NaN
           13       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           14       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           15       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           16       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           17      25.0      NaN      42.0 NaN      39.0   NaN   55.0    NaN
           18       0.0      NaN       2.0 NaN      10.0   NaN    3.0    NaN
           19       0.0      NaN       1.0 NaN       0.0   NaN    0.0    NaN
           20       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           21       2.0      NaN      19.0 NaN       0.0   NaN   30.0    NaN
           22       0.0      NaN       0.0 NaN       0.0   NaN    6.0    NaN
           23       8.0      NaN       8.0 NaN      15.0   NaN   15.0    NaN
           24      20.0      NaN      31.0 NaN      35.0   NaN   21.0    NaN
           25      42.0      NaN      62.0 NaN      52.0   NaN    0.0    NaN
           26       0.0      NaN      14.0 NaN       6.0   NaN    0.0    NaN
           27       0.0      NaN       0.0 NaN       0.0   NaN    8.0    NaN
           28       0.0      NaN       0.0 NaN       4.0   NaN    0.0    NaN
           29       1.0      NaN       2.0 NaN       0.0   NaN    0.0    NaN
           30       0.0      NaN       0.0 NaN       0.0   NaN    0.0    NaN
           31       0.0      NaN       0.0 NaN       0.0   NaN    NaN    NaN

                reading  taunton  walpole  wm
year month day
0    0     0        NaN      NaN      NaN NaN
1893 1     2        NaN    123.0      NaN NaN
           3        NaN      0.0      NaN NaN
           4        NaN      0.0      NaN NaN
           5        NaN      0.0      NaN NaN
           6        NaN    143.0      NaN NaN
           7        NaN      0.0      NaN NaN
           8        NaN      0.0      NaN NaN
           9        NaN      0.0      NaN NaN
           10       NaN     24.0      NaN NaN
           11       NaN      0.0      NaN NaN
           12       NaN      0.0      NaN NaN
           13       NaN      5.0      NaN NaN
           14       NaN      0.0      NaN NaN
           15       NaN     50.0      NaN NaN
           16       NaN      0.0      NaN NaN
           17       NaN      0.0      NaN NaN
           18       NaN     10.0      NaN NaN
           19       NaN      0.0      NaN NaN
           20       NaN      0.0      NaN NaN
           21       NaN      0.0      NaN NaN
           22       NaN      0.0      NaN NaN
           23       NaN      5.0      NaN NaN
           24       NaN      0.0      NaN NaN
           25       NaN      0.0      NaN NaN
           26       NaN      0.0      NaN NaN
           27       NaN      0.0      NaN NaN
           28       NaN      0.0      NaN NaN
           29       NaN     50.0      NaN NaN
           30       NaN      0.0      NaN NaN
...                 ...      ...      ...  ..
2014 12    2        6.0      NaN      0.0 NaN
           3       58.0      NaN     33.0 NaN
           4        0.0      NaN      9.0 NaN
           5       13.0      NaN      0.0 NaN
           6      118.0      NaN     38.0 NaN
           7       13.0      NaN     87.0 NaN
           8        0.0      NaN      0.0 NaN
           9      363.0      NaN     10.0 NaN
           10      14.0      NaN    291.0 NaN
           11      18.0      NaN     14.0 NaN
           12       1.0      NaN      2.0 NaN
           13       0.0      NaN      0.0 NaN
           14       0.0      NaN      0.0 NaN
           15       0.0      NaN      0.0 NaN
           16       0.0      NaN      0.0 NaN
           17      35.0      NaN     39.0 NaN
           18       3.0      NaN      5.0 NaN
           19       0.0      NaN      1.0 NaN
           20       0.0      NaN      0.0 NaN
           21       0.0      NaN      2.0 NaN
           22       0.0      NaN      1.0 NaN
           23      19.0      NaN     11.0 NaN
           24      53.0      NaN     11.0 NaN
           25      15.0      NaN     50.0 NaN
           26       0.0      NaN     12.0 NaN
           27       0.0      NaN      0.0 NaN
           28       1.0      NaN      0.0 NaN
           29       0.0      NaN      5.0 NaN
           30       0.0      NaN      0.0 NaN
           31       0.0      NaN      0.0 NaN

[44530 rows x 12 columns]